// ===== runtime (generated by AT Automation — do not edit) =====
const config = input.config();
const $ = { trigger: null, scope: {}, log: [] };
class Stop extends Error {}
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function wrap(table, rec) {
  const f = {};
  for (const fld of table.fields) f[fld.name] = rec.getCellValue(fld);
  return { id: rec.id, name: rec.name, table: table.name, f };
}

async function loadTrigger(tableName) {
  if (!config.recordId) throw new Error('Missing input variable "recordId"');
  const table = base.getTable(tableName);
  const rec = await table.selectRecordAsync(config.recordId);
  if (!rec) throw new Error(`Record ${config.recordId} not found in "${tableName}"`);
  $.trigger = wrap(table, rec);
}

// ---- values & templates -------------------------------------------------
function show(v) {
  if (v == null) return "";
  if (Array.isArray(v)) return v.map(show).join(", ");
  if (typeof v === "object") return String(v.name ?? v.email ?? v.url ?? v.value ?? JSON.stringify(v));
  return String(v);
}

function pick(v, key) {
  if (!key) return v;
  if (v == null) return undefined;
  if (typeof v === "object" && v.f && key in v.f) return v.f[key];
  if (typeof v === "object" && key in v) return v[key];
  const i = key.indexOf(".");
  if (i < 0) return undefined;
  return pick(pick(v, key.slice(0, i)), key.slice(i + 1));
}

function resolve(path) {
  path = path.trim();
  if ($.trigger && path in $.trigger.f) return $.trigger.f[path];
  const i = path.indexOf(".");
  const head = i < 0 ? path : path.slice(0, i);
  const rest = i < 0 ? "" : path.slice(i + 1);
  if (head === "input") return config[rest];
  if (head === "trigger") return pick($.trigger, rest);
  if (head in $.scope) return pick($.scope[head], rest);
  return undefined;
}

/** Replace {{tokens}}. A string that is exactly one token keeps its raw type. `json` escapes values for JSON bodies. */
function tpl(s, json) {
  if (typeof s !== "string") return s;
  const whole = s.match(/^\{\{([^{}]+)\}\}$/);
  if (whole && !json) return resolve(whole[1]);
  return s.replace(/\{\{([^{}]+)\}\}/g, (_, p) => {
    const t = show(resolve(p));
    return json ? JSON.stringify(t).slice(1, -1) : t;
  });
}

function toList(v) {
  if (v == null || v === "") return [];
  if (Array.isArray(v)) return v;
  if (typeof v === "object" && Array.isArray(v.records)) return v.records;
  return [v];
}

function idOf(v) {
  if (Array.isArray(v)) v = v[0];
  if (v && typeof v === "object") return v.id;
  return v == null ? "" : String(v).trim();
}

function cmp(op, l, r) {
  const arr = Array.isArray(l) ? l.map((x) => show(x).trim()) : null;
  const ls = show(l).trim(), rs = show(r).trim();
  const num = (x) => (x === "" ? NaN : Number(x));
  switch (op) {
    case "eq": return arr ? arr.includes(rs) : ls === rs;
    case "neq": return arr ? !arr.includes(rs) : ls !== rs;
    case "contains": return ls.toLowerCase().includes(rs.toLowerCase());
    case "ncontains": return !ls.toLowerCase().includes(rs.toLowerCase());
    case "startsWith": return ls.toLowerCase().startsWith(rs.toLowerCase());
    case "empty": return ls === "";
    case "nempty": return ls !== "";
    case "gt": return num(ls) > num(rs);
    case "gte": return num(ls) >= num(rs);
    case "lt": return num(ls) < num(rs);
    case "lte": return num(ls) <= num(rs);
    case "in": {
      const set = rs.split(",").map((x) => x.trim());
      return arr ? arr.some((x) => set.includes(x)) : set.includes(ls);
    }
    default: throw new Error(`Unknown operator "${op}"`);
  }
}

function check(conds, match) {
  if (!conds.length) return true;
  const res = conds.map((c) => cmp(c.op, tpl(c.left), tpl(c.right)));
  return match === "any" ? res.some(Boolean) : res.every(Boolean);
}

// ---- Airtable cells -----------------------------------------------------
function splitList(v) {
  if (Array.isArray(v)) return v;
  if (typeof v === "string") return v.split(",").map((x) => x.trim()).filter(Boolean);
  return v == null ? [] : [v];
}

function toCell(table, name, raw) {
  const field = table.getField(name);
  const v = tpl(raw);
  if (v === "" || v == null) return null;
  switch (field.type) {
    case "singleSelect": return { name: show(v) };
    case "multipleSelects": return splitList(v).map((x) => ({ name: show(x) }));
    case "multipleRecordLinks": return splitList(v).map((x) => ({ id: idOf(x) }));
    case "checkbox": return v === true || /^(true|1|yes|y|checked)$/i.test(String(v).trim());
    case "number": case "currency": case "percent": case "rating": case "duration": return Number(v);
    case "singleCollaborator": return typeof v === "object" ? { id: v.id } : String(v).includes("@") ? { email: String(v) } : { id: String(v) };
    case "multipleAttachments": return splitList(v).map((x) => ({ url: typeof x === "object" ? x.url : String(x) }));
    default: return typeof v === "object" ? show(v) : v;
  }
}

function cells(table, pairs) {
  const out = {};
  for (const p of pairs) if (p.field) out[p.field] = toCell(table, p.field, p.value);
  return out;
}

// ---- Airtable steps -----------------------------------------------------
async function findRecords(s) {
  const table = base.getTable(tpl(s.table));
  const q = await table.selectRecordsAsync();
  const out = [];
  for (const rec of q.records) {
    const row = wrap(table, rec);
    const hits = s.filters.map((f) => cmp(f.op, row.f[f.field], tpl(f.value)));
    const ok = !hits.length || (s.match === "any" ? hits.some(Boolean) : hits.every(Boolean));
    if (ok) out.push(row);
    if (s.limit > 0 && out.length >= s.limit) break;
  }
  return { records: out, count: out.length, first: out[0], ids: out.map((r) => r.id).join(",") };
}

async function getRecord(s) {
  const table = base.getTable(tpl(s.table));
  const id = idOf(tpl(s.recordId));
  if (!id) throw new Error("Record ID is empty");
  const rec = await table.selectRecordAsync(id);
  if (!rec) throw new Error(`Record ${id} not found in "${table.name}"`);
  return wrap(table, rec);
}

async function createRecord(s) {
  const table = base.getTable(tpl(s.table));
  const id = await table.createRecordAsync(cells(table, s.fields));
  await sleep(70); // stay under 15 mutations/sec
  return { id, table: table.name, f: {} };
}

async function updateRecord(s) {
  const table = base.getTable(tpl(s.table));
  const id = idOf(tpl(s.recordId));
  if (!id) throw new Error("Record ID is empty");
  await table.updateRecordAsync(id, cells(table, s.fields));
  await sleep(70);
}

async function deleteRecord(s) {
  const table = base.getTable(tpl(s.table));
  const id = idOf(tpl(s.recordId));
  if (!id) throw new Error("Record ID is empty");
  await table.deleteRecordAsync(id);
  await sleep(70);
}

// ---- Integrations -------------------------------------------------------
async function http(s) {
  const T = (v, json) => (s.raw ? v : tpl(v, json)); // raw: values are already resolved
  const headers = {};
  for (const h of s.headers) if (h.key) headers[T(h.key)] = String(s.raw ? h.value : show(tpl(h.value)));
  const body = s.body && !/^(GET|HEAD)$/i.test(s.method) ? T(s.body, /^\s*[\[{]/.test(s.body)) : undefined;
  const res = await fetch(String(T(s.url)), { method: s.method, headers, body: typeof body === "string" ? body : body == null ? undefined : JSON.stringify(body) });
  const text = await res.text();
  let parsed = text;
  try { parsed = JSON.parse(text); } catch (e) { /* plain text */ }
  if (!res.ok && !s.allowError) throw new Error(`HTTP ${res.status}: ${text.slice(0, 200)}`);
  return { status: res.status, ok: res.ok, body: parsed };
}

const JSON_H = [{ key: "Content-Type", value: "application/json" }];
const post = (url, headers, body) => http({ method: "POST", url, headers, body, raw: true });
const S = (v) => show(tpl(v));
const form = (o) => Object.keys(o).map((k) => encodeURIComponent(k) + "=" + encodeURIComponent(o[k])).join("&");

function b64(str) {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  const bytes = [...unescape(encodeURIComponent(str))].map((c) => c.charCodeAt(0)); // UTF-8 bytes
  let out = "";
  for (let i = 0; i < bytes.length; i += 3) {
    const n = (bytes[i] << 16) | ((bytes[i + 1] || 0) << 8) | (bytes[i + 2] || 0);
    out += chars[(n >> 18) & 63] + chars[(n >> 12) & 63] + (i + 1 < bytes.length ? chars[(n >> 6) & 63] : "=") + (i + 2 < bytes.length ? chars[n & 63] : "=");
  }
  return out;
}

async function slack(s) {
  await post(S(s.webhook), JSON_H, JSON.stringify({ text: S(s.text) }));
}

/** Chat notifications: slack | teams | discord (incoming webhooks) and telegram (bot API). */
async function notify(s) {
  const text = S(s.text), target = S(s.target);
  if (!target) throw new Error("Notification target is empty");
  if (s.provider === "telegram") {
    await post(`https://api.telegram.org/bot${S(s.token)}/sendMessage`, JSON_H, JSON.stringify({ chat_id: target, text }));
  } else {
    await post(target, JSON_H, JSON.stringify(s.provider === "discord" ? { content: text } : { text }));
  }
}

/** SMS / WhatsApp via Twilio (use "whatsapp:+1555…" for both numbers on WhatsApp). */
async function sms(s) {
  const sid = S(s.accountSid), auth = b64(sid + ":" + S(s.authToken));
  const body = form({ To: S(s.to), From: S(s.from), Body: S(s.body) });
  await post(`https://api.twilio.com/2010-04-01/Accounts/${sid}/Messages.json`, [{ key: "Authorization", value: "Basic " + auth }, { key: "Content-Type", value: "application/x-www-form-urlencoded" }], body);
}

async function sendEmail(s) {
  const to = S(s.to), from = S(s.from), subject = S(s.subject), text = S(s.body), key = S(s.apiKey);
  if (!to) throw new Error("Email recipient is empty");
  const bearer = [{ key: "Authorization", value: "Bearer " + key }, ...JSON_H];
  const html = !!s.html;
  switch (s.provider) {
    case "sendgrid":
      return void (await post("https://api.sendgrid.com/v3/mail/send", bearer, JSON.stringify({ personalizations: [{ to: [{ email: to }] }], from: { email: from }, subject, content: [{ type: html ? "text/html" : "text/plain", value: text }] })));
    case "mailgun": {
      const body = form({ from, to, subject, [html ? "html" : "text"]: text });
      return void (await post(`https://api.mailgun.net/v3/${S(s.domain)}/messages`, [{ key: "Authorization", value: "Basic " + b64("api:" + key) }, { key: "Content-Type", value: "application/x-www-form-urlencoded" }], body));
    }
    case "postmark":
      return void (await post("https://api.postmarkapp.com/email", [{ key: "X-Postmark-Server-Token", value: key }, { key: "Accept", value: "application/json" }, ...JSON_H], JSON.stringify({ From: from, To: to, Subject: subject, [html ? "HtmlBody" : "TextBody"]: text })));
    case "brevo":
      return void (await post("https://api.brevo.com/v3/smtp/email", [{ key: "api-key", value: key }, ...JSON_H], JSON.stringify({ sender: { email: from.replace(/^.*<|>.*$/g, "") }, to: [{ email: to }], subject, [html ? "htmlContent" : "textContent"]: text })));
    default:
      return void (await post("https://api.resend.com/emails", bearer, JSON.stringify({ from, to: [to], subject, [html ? "html" : "text"]: text })));
  }
}

/** Ask Claude. Result: { text } */
async function ai(s) {
  const system = S(s.system);
  const r = await post("https://api.anthropic.com/v1/messages",
    [{ key: "x-api-key", value: S(s.apiKey) }, { key: "anthropic-version", value: "2023-06-01" }, ...JSON_H],
    JSON.stringify({ model: s.model || "claude-sonnet-5-5", max_tokens: Number(s.maxTokens) || 512, ...(system ? { system } : {}), messages: [{ role: "user", content: S(s.prompt) }] }));
  const text = ((r.body && r.body.content) || []).map((c) => c.text || "").join("").trim();
  return { text, status: r.status };
}

async function wait(s) {
  await sleep(Math.min(25, Math.max(0, Number(S(s.seconds)) || 1)) * 1000);
}

const day = (d) => d.toISOString().slice(0, 10);
function transform(s) {
  const str = S(s.input), arg = S(s.arg), n = Number(str), m = Number(arg);
  switch (s.op) {
    case "upper": return str.toUpperCase();
    case "lower": return str.toLowerCase();
    case "trim": return str.trim();
    case "length": return str.length;
    case "replace": { const [from, to = ""] = arg.split("=>"); return str.split(from).join(to); }
    case "today": return day(new Date());
    case "addDays": { const d = str ? new Date(str) : new Date(); d.setDate(d.getDate() + (m || 0)); return day(d); }
    case "add": return n + m;
    case "subtract": return n - m;
    case "multiply": return n * m;
    case "divide": return m ? n / m : 0;
    case "round": return Number(n.toFixed(m || 0));
    default: throw new Error(`Unknown transform "${s.op}"`);
  }
}

/** Find a record whose `matchField` equals `matchValue`; update it, or create it if missing. */
async function upsertRecord(s) {
  const table = base.getTable(tpl(s.table));
  const q = await table.selectRecordsAsync();
  const want = S(s.matchValue).trim();
  const hit = q.records.find((r) => show(r.getCellValue(s.matchField)).trim() === want);
  if (hit) { await table.updateRecordAsync(hit.id, cells(table, s.fields)); await sleep(70); return { id: hit.id, created: false, f: {} }; }
  const id = await table.createRecordAsync(cells(table, s.fields));
  await sleep(70);
  return { id, created: true, f: {} };
}

// ---- Execution ----------------------------------------------------------
async function step(name, fn, soft) {
  try {
    await fn();
    $.log.push("✓ " + name);
  } catch (e) {
    if (e instanceof Stop) throw e;
    $.log.push("✗ " + name + ": " + e.message);
    if (!soft) {
      output.set("log", $.log.join("\n"));
      throw new Error(`Step "${name}" failed: ${e.message}`);
    }
  }
}

async function runMain(main) {
  try {
    await main();
  } catch (e) {
    if (!(e instanceof Stop)) throw e;
    $.log.push("■ stopped");
  }
  output.set("log", $.log.join("\n"));
}

// ---- Workflow engine: runs workflow JSON (router, condition, loop, find, create, …) ----
const AsyncFunction = Object.getPrototypeOf(async function () {}).constructor;

async function execSteps(steps) {
  for (const s of steps) {
    if (s.disabled) continue;
    if (s.type === "stop") throw new Stop();
    await step(s.label && s.label.trim() ? s.label.trim() : s.type, () => execOne(s), s.continueOnError);
  }
}

async function execOne(s) {
  switch (s.type) {
    case "find": $.scope[s.saveAs || "found"] = await findRecords(s); break;
    case "get": $.scope[s.saveAs || "record"] = await getRecord(s); break;
    case "create": $.scope[s.saveAs || "created"] = await createRecord(s); break;
    case "update": await updateRecord(s); break;
    case "delete": await deleteRecord(s); break;
    case "http": $.scope[s.saveAs || "response"] = await http(s); break;
    case "slack": await slack(s); break;
    case "email": await sendEmail(s); break;
    case "notify": await notify(s); break;
    case "sms": await sms(s); break;
    case "ai": $.scope[s.saveAs || "ai"] = await ai(s); break;
    case "wait": await wait(s); break;
    case "transform": $.scope[s.saveAs || "result"] = transform(s); break;
    case "upsert": $.scope[s.saveAs || "record"] = await upsertRecord(s); break;
    case "setVar": $.scope[s.name] = tpl(s.value); break;
    case "output": output.set(s.key, show(tpl(s.value))); break;
    case "code": await new AsyncFunction("$", "base", "output", "tpl", "resolve", "show", "fetch", "config", s.code)($, base, output, tpl, resolve, show, fetch, config); break;
    case "if": await execSteps(check(s.conds, s.match) ? s.then : s.else); break;
    case "loop":
      for (const item of toList(tpl(s.source))) { $.scope[s.as || "item"] = item; await execSteps(s.steps); }
      break;
    case "switch": {
      const v = show(tpl(s.value)).trim();
      const c = s.cases.find((x) => String(x.value).trim() === v);
      await execSteps(c ? c.steps : s.default);
      break;
    }
    default: throw new Error(`Unknown step type "${s.type}"`);
  }
}

async function runWorkflow(w) {
  await loadTrigger(w.trigger.dynamic ? config.tableName : w.trigger.table);
  if (w.trigger.guard.length && !check(w.trigger.guard, w.trigger.guardMatch)) {
    output.set("skipped", "guard conditions not met");
    return;
  }
  await runMain(() => execSteps(w.steps));
}

const __rt = { execOne, runWorkflow, $, config, Stop, sleep, wrap, resolve, show, tpl, toList, idOf, cmp, check, loadTrigger, findRecords, getRecord, createRecord, updateRecord, deleteRecord, http, slack, sendEmail, step, runMain };
// ===== end runtime =====
return __rt;
